name : End-to-End testing with tR
#just testing stuff
on:
  push:
    branches: main #[tR-e2e-tests]
  pull_request:
    branches: main #[tR-e2e-tests]
  workflow_dispatch:

jobs:
  e2e-tests-tR:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: Hello world! 
